bed: rewrite pog

diff --git a/bed b/bed
--- a/bed
+++ b/bed
@@ -2,229 +2,146 @@
 
 declare -a buffer
 declare -i line base
-declare file version message
-bind 'set disable-completion on' 2>/dev/null
+declare file message
 
-line=0
-base=1
-file="bed.txt"
-version="INDEV"
-message="🛏  Welcome to bed"
-unsaved_changes=0
+buffer=() # File contents
+line=0 # Currently selected line (0 means the buffer is empty)
+base=1 # Top-most line shown
+file= # Currently addressed file
+message="Welcome to bed (press 'q' to quit)." # Feedback text in the status bar
+modified=false # Tracking whether a file was modified
 
-shopt -s checkwinsize; (:)
-trap refresh WINCH ALRM
-trap cleanup EXIT INT HUP USR1
+shopt -s extglob # Ensure advanced pattern matching is available
+shopt -s checkwinsize; (:) # Enable and then trigger a terminal size refresh
+trap redraw WINCH ALRM # Attach WINCH and ALRM to redraw the screen
+trap die EXIT INT HUP USR1 # Attach most exit codes to cleanup and exit
 
-startup() {
-    cursor hide && cursor spos && cursor save
-}
-
-cleanup() {
-    cursor show && cursor rpos && cursor load
-    exit
-}
-
-cursor() {
-    case "$1" in
-    save) printf "\e[?47h";;
-    load) printf "\e[?47l";;
-    spos) printf "\e7";;
-    rpos) printf "\e8\e[B";;
-    hide) printf "\e[?25l";;
-    show) printf "\e[?25h";;
-    goto) printf "\e[%s;%sf" "$2" "$3";;
-    esac
-    return 1
-}
-
-refresh() {
-    clear
-    printf "\e[100m %s (%s Lines) %s %sx%s %s \e[m\n" \
-        "$file" "${#buffer[@]}" "$version" "$LINES" "$COLUMNS" "$base"
-    for ((i=base; i-base < LINES-3; i++)); do
-        ((i !=  line))        && printf "\e[90m"
-        ((i > ${#buffer[@]})) && printf "   ~\e[m\n" || printf "%4s\e[m %s\n" "$i" "${buffer[i]}"
-    done
-    printf "\e[34m%s\e[m\n" "$message"
-}
-
-file_read() {
-    file_set "$1" || return 1
-    mapfile -t -O 1 buffer <"$file"
-    line=1
-    message="Read ${#buffer[@]} lines from '$file'"
-}
-
-file_set() {
-    [ "$1" ] && file=$1 || return 1
-    message="Set file path to '$file'"
-}
-
-file_write() {
-    : >"$file"
-    for wline in "${buffer[@]}"; do echo "$wline" >>"$file"; done
-    message="Wrote ${buffer[@]} lines to '$file'"   
-    unsaved_changes=0
-}
-
-line_up() {
-    for ((i=0;i<$1;i++)); do
-        ((line > 1))    && ((line--))
-        ((line < base)) && ((base--))
-        ((base <= 0))   && base=1
-    done
-}
-
-line_down() {
-    for ((i=0;i<$1;i++)); do
-        ((line < ${#buffer[@]})) && ((line++))
-        ((line > base+LINES-4))  && ((base++))
-    done
-}
-
-line_delete() {
-    buffer=([0]="" "${buffer[@]:1:line-1}" "${buffer[@]:line+1}")
-    unset "buffer[0]"
-    ((line > ${#buffer[@]})) && ((line--))
-    unsaved_changes=1 #Set unsaved changes to 1
-}
-
-line_insert() {
-    buffer=([0]="" "${buffer[@]:1:line}" "" "${buffer[@]:line+1}")
-    unset "buffer[0]"
-    ((line++))
-    refresh
-    line_edit
-}
-
-line_blank() {
-    buffer=([0]="" "${buffer[@]:1:line}" "" "${buffer[@]:line+1}")
-    unset "buffer[0]"
-}
-
-line_append() {
-    cursor goto $((line-base + 2)) $((${#buffer[line]} + 6)) && cursor show
-    read -re
-    cursor hide
-    buffer[line]+=$REPLY
-    unsaved_changes=1 #Set unsaved changes to 1
-}
-
-line_clear() {
-    ((line == 0)) && return
-    cursor goto $((line-base + 2)) 6
-    buffer[line]=""
-    unsaved_changes=1
-}
-
-line_clear() {
-    ((line == 0)) && return
-    cursor goto $((line-base + 2)) 6
-    buffer[line]=""
-}
-
-line_edit() {
-    ((line == 0)) && return
-    cursor goto $((line-base + 2)) 6 && cursor show
-    read -rei "${buffer[line]}"
-    cursor hide
-    #Update line if changed
-    if [ "${buffer[line]}" != "$REPLY" ]; then
-        buffer[line]=$REPLY
-        unsaved_changes=1 #Set unsaved changes to 1
+set_buffer_file() {
+    bind 'set disable-completion off' 2>/dev/null # Enable completion
+    printf '\e[?25h' # Enable cursor
+    if read -rei "$1$file" -p "Path: " file; then
+        modified=true
     fi
+    bind 'set disable-completion on' 2>/dev/null
 }
 
-file_prompt () {
-    bind 'set disable-completion off' 2>/dev/null
-    read -rep "> " choice
-    bind 'set disable-completion on'
-    printf "$choice"
-}
-
-quit () {
-    if [ "$unsaved_changes" -ne 0 ]; then
-        message="File $file was modified, save before close? [Y/n/c] "
-        while [ 1 ]; do #Iterate until a valid answer is provided
-            refresh
-            read -n 1
-            if [[ $REPLY =~ ^[Yy]$ ]]; then
-                file_write
-                refresh
-                exit 0
-            elif [[ $REPLY =~ ^[Nn]$ ]]; then
-                exit 0
-            elif [[ $REPLY =~ ^[Cc]$ ]]; then
-                message="Quit cancelled"
-                break #Break and return
-            else
-                continue #Invalid answer, keep iterating
-            fi
-        done
+read_buffer() {
+    set_buffer_file "$1" # Update target file (pass on default if present)
+    mapfile -t -O 1 buffer <"$file" # Read file into an array
+    if [[ "${buffer[1]}" ]]; then # Ensure that something was actually read into the file
+        line=1 # Indicate that we have a buffer loaded
+        message="Read ${#buffer[@]} lines from '$file'"
     else
-        exit 0
+        message="'$file' is empty"
     fi
-    #Return performing no action
 }
 
-keyboard_loop () {
-    startup
-    file_read "$1" && message="🛏  Welcome to bed ($message)"
-    refresh
+write_buffer() {
+    true >"$file" # Set the file to an empty text file
+    for ln in "${buffer[@]}"; do # Write in the buffer to the file
+        echo "$ln" >>"$file"
+    done
+    message="Wrote ${#buffer[@]} lines to '$file'"
+}
 
-    declare -a key
-    while read -rsN1 -t0.02 key[0] || true; do
-        # If a timeout occured, do nothing
-        [ "${key[0]}" ] || continue
+get_help() {
+    man bed || message="Failed to get help"
+}
 
-        # Nasty hack for multibyte input
-        read -rsN1 -t 0.0001 key[1]
-        read -rsN1 -t 0.0001 key[2]
-        read -rsN1 -t 0.0001 key[3]
+edit_line() {
+    ((line == 0)) && return # If the line is not possible, do nothing
+    printf '\e[?25h\e[%sH' "$((line + 2 - base))" # Reset cursor position and enable cursor
+    read -rei "${buffer[line]}" -p "$(printf '%4s ' "$line")" # Present editable line
+    if [[ "$REPLY" != "${buffer[line]}" ]]; then # If the line is changed, update and inform
+        buffer[line]=$REPLY
+        modified=true
+    fi
+}
 
-        # Compute key presses
-        case "$(printf %s "${key[@]}")" in
-        $'\e[A'|$'\e0A') line_up 1;;
-        $'\e[B'|$'\e0B') line_down 1;;
-        $'\e[5~'|$'\e05~') line_up $((LINES - 4));;
-        $'\e[6~'|$'\e06~') line_down $((LINES - 4));;
-        a) line_append;;
-        b) line_blank;;
-        c) line_clear;;
-        d) line_delete;;
-        e) line_edit;;
-        f) file_set $(file_prompt);;
-        i) line_insert;;
-        l) file_read $(file_prompt);;
-        q) quit;;
-        w) file_write;;
-        esac
+new_line() {
+    buffer=("" "${buffer[@]:1:line}" "" "${buffer[@]:line+1}")
+    unset 'buffer[0]'
+}
 
-        # Refresh the UI
-        refresh
+append_line() {
+    new_line
+    down
+    redraw
+    edit_line
+}
+
+delete_line() {
+    buffer=("" "${buffer[@]:1:line-1}" "${buffer[@]:line+1}")
+    unset 'buffer[0]'
+    ((line > ${#buffer[@]})) && up
+    modified=true
+}
+
+up() {
+    for ((i = 0; i < ${1:-1}; i++)); do
+        ((line > 1)) && ((line--)) # As long as we can keep going up, go up
+        ((line < base)) && ((base--)) # Push back the top if we need to
+        ((base <= 0)) && base=1 # Don't push back if our base is at 1
     done
 }
 
-usage () {
-cat <<EOF
-${0##*/}: bash text editor
-
-usage: ${0##*/} [options] [file]
-
-options:
-    -h|--help: print this help message
-
-open file for editing.
-if file is not given, default to bed.txt.
-EOF
+down() {
+    for ((i = 0; i < ${1:-1}; i++)); do
+        ((line < ${#buffer[@]})) && ((line++)) # If we can go down, go down
+        ((line > base + LINES - 3)) && ((base++)) # Move window down if needed
+    done
 }
 
-main () {
-    case $1 in
-        -h|--help) trap : EXIT; usage;;
-        *) keyboard_loop "$1";;
+die() {
+    bind 'set disable-completion off' 2>/dev/null # Enable completion
+    printf '\e[?25h\e[?7h\e[?1047l' # Reset terminal to sane mode
+    exit "${errno:-0}" # Assume that we're exiting without an error
+}
+
+redraw() {
+    (printf '\e[2J\e[?25l\e[100m%*s\r %s \e[46;30m %s \e[0;100m L%s W%s\e[m' \
+        "$COLUMNS" "$message" "${BED_ICON:=🛏 }" \
+        "${file:-N/A}" "$line" "${#buffer[line]}") # Status line, among others
+    for ((i = base; i - base < LINES - 2; i++)); do # Iterate over shown lines
+        ((i != line)) && printf '\e[90m' # Fade line number if not selected
+        ((i > ${#buffer[@]})) && printf '\n   ~\e[m' || \
+            printf '\n%4s\e[m %s' "$i" "${buffer[i]}" # Print the line
+    done
+    printf '\n' # Add final newline to seperate commandline
+}
+
+key() {
+    case "$1" in
+    ${BED_KEY_PGUP:=$'\E[5~'}) up $((LINES - 3));;
+    ${BED_KEY_PGDN:=$'\E[6~'}) down $((LINES - 3));;
+    ${BED_KEY_UP:=$'\E[A'}*) up;;
+    ${BED_KEY_DOWN:=$'\E[B'}*) down;;
+    ${BED_KEY_HELP:=$'\b'}) get_help;; # Open the manpage (breaks stuff)
+    ${BED_KEY_QUIT:=q}) die;; # TODO replace with editor_quit()
+    ${BED_KEY_FILE:=f}) set_buffer_file;;
+    ${BED_KEY_READ:=r}) read_buffer;;
+    ${BED_KEY_WRITE:=w}) write_buffer;;
+    ${BED_KEY_EDIT:=e}|'') edit_line;;
+    ${BED_KEY_APPEND:=a}) append_line;;
+    ${BED_KEY_DELETE:=d}) delete_line;;
+    ${BED_KEY_NEW:=n}) new_line;;
     esac
+}
+
+main() {
+    printf '\e[?1047h' # Switch to alternative buffer
+    if [[ "$1" ]]; then # If a file was provided in the terminal pre-load it
+        redraw # Draw out the UI before loading file
+        read_buffer "$1"
+    fi
+    while redraw; do # Keep redrawing when we can (allow WINCH signals to get handled)
+        local -a k=()
+        local -i i=1
+        if read -rsN1 -t0.1 k[0]; then # Check for ready input
+            while read -rsN1 -t0.0001 k[$i]; do ((i++)); done # Multibyte hack
+            key "$(printf '%s' "${k[@]}")" # Handle keypress event
+        fi
+    done
 }
 
 main "$@"
